export const availableWords = [
  "abajur",
  "televisão",
  "rádio",
  "carro",
  "sofá",
  "mesa",
  "geladeira",
  "micro-ondas",
  "cama",
  "computador",
  "livro",
  "cadeira",
  "armário",
  "fogão",
  "ventilador",
  "máquina de lavar",
  "microfone",
  "refrigerador",
  "batedeira",
  "torradeira",
  "tapete",
  "quadros",
  "cortina",
  "bicicleta",
  "aspirador",
  "cafeteira",
  "colchão",
  "escova",
  "cadeira de escritório",
  "luminária",
  "móvel de TV",
  "armário de cozinha",
  "livro de receitas",
  "lousa",
  "jogo de panelas",
  "garrafa",
  "toalha",
  "penteadeira",
  "escrivaninha",
  "abajur de mesa",
  "cesta",
  "espelho",
  "cubo de gelo",
  "ventilador de teto",
  "mesa de jantar",
  "cadeira de jantar",
  "prateleira",
  "puf",
  "porta-retratos",
  "chaveiro",
  "caixa de som",
  "console de videogame",
  "reproductor de DVD",
  "painel solar",
  "tábua de passar",
  "secador de cabelo",
  "ferro de passar",
  "escada",
  "jardineira",
  "banco",
  "sofá-cama",
  "cômoda",
  "armário de banheiro",
  "cadeira de balanço",
  "balança",
  "piso",
  "lixeira",
  "cesto de roupa suja",
  "barbecue",
  "relógio",
  "quadro branco",
  "assadeira",
  "abridor de garrafas",
  "espremedor de frutas",
  "câmera",
  "gaiola",
  "aquário",
  "fogão a lenha",
  "caixa de ferramentas",
  "carrinho de bebê",
  "cadeira de rodas",
  "portátil",
  "almofada",
  "lanterna",
  "raquete",
  "tapete de yoga",
  "sacola",
  "bolsa",
  "janela"
]
